--
-- Truncate table before insert `#__qazap_cartattributes`
--

TRUNCATE TABLE `#__qazap_cartattributes`;
--
-- Dumping data for table `#__qazap_cartattributes`
--

INSERT INTO `#__qazap_cartattributes` (`id`, `typeid`, `value`, `price`, `stock`, `ordered`, `booked_order`, `product_id`, `ordering`) VALUES
(4, 1, 'White', 0.0000000000, 10000, 0, 0, 4, 0),
(5, 1, 'Black', 0.0000000000, 0, 0, 0, 4, 1),
(6, 1, 'Black', 0.0000000000, 10000, 0, 0, 2, 0),
(7, 1, 'White', 100.0000000000, 10000, 0, 0, 2, 1),
(8, 1, 'Black', 0.0000000000, 10000, 0, 0, 6, 0),
(9, 1, 'Grey', 0.0000000000, 0, 0, 0, 6, 1),
(14, 2, '8', 0.0000000000, 10000, 0, 0, 15, 0),
(15, 2, '9', 0.0000000000, 10000, 0, 0, 15, 1),
(16, 2, '10', 0.0000000000, 0, 0, 0, 15, 2),
(17, 2, '11', 5.0000000000, 10000, 0, 0, 15, 3),
(22, 2, '7', 0.0000000000, 10000, 0, 0, 14, 0),
(23, 2, '8', 0.0000000000, 10000, 0, 0, 14, 1),
(24, 2, '9', 0.0000000000, 10000, 0, 0, 14, 2),
(25, 2, '10', 0.0000000000, 10000, 0, 0, 14, 3),
(26, 2, '7', 0.0000000000, 10000, 0, 0, 16, 0),
(27, 2, '8', 0.0000000000, 10000, 0, 0, 16, 1),
(28, 2, '9', 0.0000000000, 10000, 0, 0, 16, 2),
(29, 2, '10', 0.0000000000, 10000, 0, 0, 16, 3);

--
-- Truncate table before insert `#__qazap_cartattributestype`
--

TRUNCATE TABLE `#__qazap_cartattributestype`;
--
-- Dumping data for table `#__qazap_cartattributestype`
--

INSERT INTO `#__qazap_cartattributestype` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `type`, `title`, `show_title`, `description`, `tooltip`, `hidden`, `check_stock`, `params`, `created_by`, `created_time`, `modified_by`, `modified_time`) VALUES
(1, 1, 1, NULL, NULL, {{[radioplugin_id]}}, 'Color', 1, '', '', 0, 1, '{"display_price":"1","display_stock":"1"}', {{[superAdmin_id]}}, '2014-09-11 14:29:34', 0, '0000-00-00 00:00:00'),
(2, 2, 1, NULL, NULL, {{[listplugin_id]}}, 'Size', 1, '', '', 0, 1, '{"display_price":"1","display_stock":"1"}', {{[superAdmin_id]}}, '2014-09-11 14:30:09', 0, '0000-00-00 00:00:00');

--
-- Truncate table before insert `#__qazap_categories`
--

TRUNCATE TABLE `#__qazap_categories`;
--
-- Dumping data for table `#__qazap_categories`
--

INSERT INTO `#__qazap_categories` (`category_id`, `asset_id`, `parent_id`, `lft`, `rgt`, `level`, `note`, `images`, `published`, `checked_out`, `checked_out_time`, `access`, `params`, `created_user_id`, `created_time`, `modified_user_id`, `modified_time`, `hits`, `version`) VALUES
(1, 0, 0, 0, 17, 0, '', '', 1, 0, '0000-00-00 00:00:00', 1, '', 0, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0, 1),
(2, 60, 1, 1, 2, 1, '', '{"name":"mobiles.jpg","url":"\\/images\\/qazap\\/images\\/mobiles.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"mobiles.jpg","medium_url":"\\/images\\/qazap\\/images\\/medium\\/mobiles.jpg","thumbnail_url":"\\/images\\/qazap\\/images\\/thumbnail\\/mobiles.jpg"}', 1, 0, '0000-00-00 00:00:00', 1, '{"category_layout":"_:default","show_category_title":"1","show_category_description":"1","show_category_image":"1","display_subcategories":"1","subcategories_per_row":"4","show_subcategory_title":"1","show_subcategory_image":"1","show_subcategory_num_products":"1","show_empty_subcategories":"1","show_no_products":"1"}', {{[superAdmin_id]}}, '2014-09-10 13:40:45', {{[superAdmin_id]}}, '2014-09-12 10:42:53', 0, 1),
(3, 61, 1, 3, 4, 1, '', '{"name":"canon1.jpg","url":"\\/images\\/qazap\\/images\\/canon1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"canon1.jpg","medium_url":"\\/images\\/qazap\\/images\\/medium\\/canon1.jpg","thumbnail_url":"\\/images\\/qazap\\/images\\/thumbnail\\/canon1.jpg"}', 1, 0, '0000-00-00 00:00:00', 1, '{"category_layout":"_:default","show_category_title":"1","show_category_description":"1","show_category_image":"1","display_subcategories":"1","subcategories_per_row":"4","show_subcategory_title":"1","show_subcategory_image":"1","show_subcategory_num_products":"1","show_empty_subcategories":"1","show_no_products":"1"}', {{[superAdmin_id]}}, '2014-09-10 13:42:31', {{[superAdmin_id]}}, '2014-09-12 10:52:36', 0, 1),
(4, 62, 1, 5, 6, 1, '', '{"name":"television.jpg","url":"\\/images\\/qazap\\/images\\/television.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"television.jpg","medium_url":"\\/images\\/qazap\\/images\\/medium\\/television.jpg","thumbnail_url":"\\/images\\/qazap\\/images\\/thumbnail\\/television.jpg"}', 1, 0, '0000-00-00 00:00:00', 1, '{"category_layout":"_:default","show_category_title":"1","show_category_description":"1","show_category_image":"1","display_subcategories":"1","subcategories_per_row":"4","show_subcategory_title":"1","show_subcategory_image":"1","show_subcategory_num_products":"1","show_empty_subcategories":"1","show_no_products":"1"}', {{[superAdmin_id]}}, '2014-09-10 13:43:02', {{[superAdmin_id]}}, '2014-09-12 11:18:17', 0, 1),
(5, 63, 1, 7, 8, 1, '', '{"name":"footwears.jpg","url":"\\/images\\/qazap\\/images\\/footwears.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"footwears.jpg","medium_url":"\\/images\\/qazap\\/images\\/medium\\/footwears.jpg","thumbnail_url":"\\/images\\/qazap\\/images\\/thumbnail\\/footwears.jpg"}', 1, 0, '0000-00-00 00:00:00', 1, '{"category_layout":"_:default","show_category_title":"1","show_category_description":"1","show_category_image":"1","display_subcategories":"1","subcategories_per_row":"4","show_subcategory_title":"1","show_subcategory_image":"1","show_subcategory_num_products":"1","show_empty_subcategories":"1","show_no_products":"1"}', {{[superAdmin_id]}}, '2014-09-10 13:43:30', {{[superAdmin_id]}}, '2014-09-12 11:18:40', 0, 1),
(6, 64, 1, 9, 14, 1, '', '{"name":"fashion_unlimited.jpg","url":"\\/images\\/qazap\\/images\\/fashion_unlimited.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"fashion_unlimited.jpg","medium_url":"\\/images\\/qazap\\/images\\/medium\\/fashion_unlimited.jpg","thumbnail_url":"\\/images\\/qazap\\/images\\/thumbnail\\/fashion_unlimited.jpg"}', 1, 0, '0000-00-00 00:00:00', 1, '{"category_layout":"_:default","show_category_image":"0","subcategories_per_row":"4","show_no_products":"0"}', {{[superAdmin_id]}}, '2014-09-10 13:44:32', {{[superAdmin_id]}}, '2014-09-12 12:15:46', 0, 1),
(7, 65, 1, 15, 16, 1, '', '{"name":"gift-set.jpg","url":"\\/images\\/qazap\\/images\\/gift-set.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"gift-set.jpg","medium_url":"\\/images\\/qazap\\/images\\/medium\\/gift-set.jpg","thumbnail_url":"\\/images\\/qazap\\/images\\/thumbnail\\/gift-set.jpg"}', 1, 0, '0000-00-00 00:00:00', 1, '{"category_layout":"_:default","show_category_title":"1","show_category_description":"1","show_category_image":"1","display_subcategories":"1","subcategories_per_row":"4","show_subcategory_title":"1","show_subcategory_image":"1","show_subcategory_num_products":"1","show_empty_subcategories":"1","show_no_products":"1"}', {{[superAdmin_id]}}, '2014-09-10 13:45:08', {{[superAdmin_id]}}, '2014-09-12 11:19:14', 0, 1),
(8, 66, 6, 10, 11, 2, '', '{"name":"mens fashion.jpg","url":"\\/images\\/qazap\\/images\\/mens%20fashion.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"mens fashion.jpg","medium_url":"\\/images\\/qazap\\/images\\/medium\\/mens%20fashion.jpg","thumbnail_url":"\\/images\\/qazap\\/images\\/thumbnail\\/mens%20fashion.jpg"}', 1, 0, '0000-00-00 00:00:00', 1, '{"category_layout":"_:default","show_category_title":"1","show_category_description":"1","show_category_image":"1","display_subcategories":"1","subcategories_per_row":"4","show_subcategory_title":"1","show_subcategory_image":"1","show_subcategory_num_products":"1","show_empty_subcategories":"1","show_no_products":"1"}', {{[superAdmin_id]}}, '2014-09-10 13:46:53', {{[superAdmin_id]}}, '2014-09-12 11:18:52', 0, 1),
(9, 67, 6, 12, 13, 2, '', '{"name":"womens fashion.jpg","url":"\\/images\\/qazap\\/images\\/womens%20fashion.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"womens fashion.jpg","medium_url":"\\/images\\/qazap\\/images\\/medium\\/womens%20fashion.jpg","thumbnail_url":"\\/images\\/qazap\\/images\\/thumbnail\\/womens%20fashion.jpg"}', 1, 0, '0000-00-00 00:00:00', 1, '{"category_layout":"_:default","show_category_title":"1","show_category_description":"1","show_category_image":"1","display_subcategories":"1","subcategories_per_row":"4","show_subcategory_title":"1","show_subcategory_image":"1","show_subcategory_num_products":"1","show_empty_subcategories":"1","show_no_products":"1"}', {{[superAdmin_id]}}, '2014-09-10 13:47:57', {{[superAdmin_id]}}, '2014-09-12 11:19:03', 0, 1);

--
-- Truncate table before insert `#__qazap_category_details`
--

TRUNCATE TABLE `#__qazap_category_details`;
--
-- Dumping data for table `#__qazap_category_details`
--

INSERT INTO `#__qazap_category_details` (`category_details_id`, `category_id`, `path`, `title`, `alias`, `description`, `metadesc`, `metakey`, `metadata`, `language`) VALUES
(1, 1, '', 'ROOT', 'root', '', '', '', '', '*'),
(2, 2, 'mobile-handsets', 'Mobile Handsets', 'mobile-handsets', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>', '', '', '{"page_title":"","author":"","robots":""}', 'en-GB'),
(3, 3, 'cameras', 'Cameras', 'cameras', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>', '', '', '{"page_title":"","author":"","robots":""}', 'en-GB'),
(4, 4, 'televisions', 'Televisions', 'televisions', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>', '', '', '{"page_title":"","author":"","robots":""}', 'en-GB'),
(5, 5, 'footwears', 'Footwears', 'footwears', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>', '', '', '{"page_title":"","author":"","robots":""}', 'en-GB'),
(6, 6, 'dresses', 'Dresses', 'dresses', '<p><img src="images/qazap/men-banner.jpg" alt="Dresses Banner" /></p>', '', '', '{"page_title":"","author":"","robots":""}', 'en-GB'),
(7, 7, 'gift-sets', 'Gift Sets', 'gift-sets', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>', '', '', '{"page_title":"","author":"","robots":""}', 'en-GB'),
(8, 8, 'dresses/men', 'Men', 'men', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>', '', '', '{"page_title":"","author":"","robots":""}', 'en-GB'),
(9, 9, 'dresses/women', 'Women', 'women', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>', '', '', '{"page_title":"","author":"","robots":""}', 'en-GB');

--
-- Truncate table before insert `#__qazap_customfield`
--

TRUNCATE TABLE `#__qazap_customfield`;
--
-- Dumping data for table `#__qazap_customfield`
--

INSERT INTO `#__qazap_customfield` (`id`, `typeid`, `value`, `product_id`, `ordering`) VALUES
(1, 1, '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 9, 0),
(2, 1, '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<p>', 8, 0);

--
-- Truncate table before insert `#__qazap_customfieldtype`
--

TRUNCATE TABLE `#__qazap_customfieldtype`;
--
-- Dumping data for table `#__qazap_customfieldtype`
--

INSERT INTO `#__qazap_customfieldtype` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `type`, `title`, `show_title`, `description`, `tooltip`, `layout_position`, `hidden`, `params`, `created_by`, `created_time`, `modified_by`, `modified_time`) VALUES
(1, 1, 1, NULL, NULL, {{[textareaplugin_id]}}, 'Technical Specification', 1, '', '', '', 0, '', {{[superAdmin_id]}}, '2014-09-11 14:28:50', 0, '0000-00-00 00:00:00');

--
-- Truncate table before insert `#__qazap_manufacturercategories`
--

TRUNCATE TABLE `#__qazap_manufacturercategories`;
--
-- Dumping data for table `#__qazap_manufacturercategories`
--

INSERT INTO `#__qazap_manufacturercategories` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `manufacturer_category_name`, `alias`, `manufacturer_category_description`, `created_by`, `created_time`, `modified_by`, `modified_time`) VALUES
(1, 1, 1, 0, '0000-00-00 00:00:00', 'Default Category', 'default-category', '', {{[superAdmin_id]}}, '2014-09-11 07:37:54', {{[superAdmin_id]}}, '2014-09-11 07:38:30');

--
-- Truncate table before insert `#__qazap_manufacturers`
--

TRUNCATE TABLE `#__qazap_manufacturers`;
--
-- Dumping data for table `#__qazap_manufacturers`
--

INSERT INTO `#__qazap_manufacturers` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `manufacturer_name`, `alias`, `manufacturer_email`, `manufacturer_category`, `description`, `manufacturer_url`, `images`, `created_by`, `created_time`, `modified_by`, `modified_time`) VALUES
(1, 4, 1, 0, '0000-00-00 00:00:00', 'Canon', 'canon', 'info@canon.com', 1, '', 'www.canon.com', '[{"name":"canon-logo.jpg","url":"\\/images\\/qazap\\/brands\\/canon-logo.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"canon-logo.jpg","medium_url":"\\/images\\/qazap\\/brands\\/medium\\/canon-logo.jpg","thumbnail_url":"\\/images\\/qazap\\/brands\\/thumbnail\\/canon-logo.jpg"}]', {{[superAdmin_id]}}, '2014-09-11 07:59:58', {{[superAdmin_id]}}, '2014-09-12 11:53:04'),
(2, 6, 1, NULL, NULL, 'Nikon', 'nikon', 'info@nikon.com', 1, '', 'www.nikon.com', '[{"name":"nikon-logo.jpg","url":"\\/images\\/qazap\\/brands\\/nikon-logo.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"nikon-logo.jpg","medium_url":"\\/images\\/qazap\\/brands\\/medium\\/nikon-logo.jpg","thumbnail_url":"\\/images\\/qazap\\/brands\\/thumbnail\\/nikon-logo.jpg"}]', {{[superAdmin_id]}}, '2014-09-11 08:01:11', {{[superAdmin_id]}}, '2014-09-12 11:53:13'),
(3, 2, 1, NULL, NULL, 'Apple', 'apple', 'info@apple.com', 1, '', 'www.apple.com', '[{"name":"apple-logo.jpg","url":"\\/images\\/qazap\\/brands\\/apple-logo.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"apple-logo.jpg","medium_url":"\\/images\\/qazap\\/brands\\/medium\\/apple-logo.jpg","thumbnail_url":"\\/images\\/qazap\\/brands\\/thumbnail\\/apple-logo.jpg"}]', {{[superAdmin_id]}}, '2014-09-11 08:01:53', {{[superAdmin_id]}}, '2014-09-12 11:53:00'),
(4, 5, 1, NULL, NULL, 'HTC', 'htc', 'info@htc.com', 1, '', 'www.htc.com', '[{"name":"htc-logo.jpg","url":"\\/images\\/qazap\\/brands\\/htc-logo.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"htc-logo.jpg","medium_url":"\\/images\\/qazap\\/brands\\/medium\\/htc-logo.jpg","thumbnail_url":"\\/images\\/qazap\\/brands\\/thumbnail\\/htc-logo.jpg"}]', {{[superAdmin_id]}}, '2014-09-11 08:02:31', {{[superAdmin_id]}}, '2014-09-12 11:53:13'),
(5, 3, 1, NULL, NULL, 'Blackberry', 'blackberry', 'info@blackberry.com', 1, '', 'www.blackberry.com', '[{"name":"blackberry-logo.jpg","url":"\\/images\\/qazap\\/brands\\/blackberry-logo.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"blackberry-logo.jpg","medium_url":"\\/images\\/qazap\\/brands\\/medium\\/blackberry-logo.jpg","thumbnail_url":"\\/images\\/qazap\\/brands\\/thumbnail\\/blackberry-logo.jpg"}]', {{[superAdmin_id]}}, '2014-09-11 08:03:15', {{[superAdmin_id]}}, '2014-09-12 11:53:04'),
(6, 7, 1, NULL, NULL, 'Samsung', 'samsung', 'info@samsung.com', 1, '', 'www.samsung.com', '[{"name":"samsung-logo.jpg","url":"\\/images\\/qazap\\/brands\\/samsung-logo.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"samsung-logo.jpg","medium_url":"\\/images\\/qazap\\/brands\\/medium\\/samsung-logo.jpg","thumbnail_url":"\\/images\\/qazap\\/brands\\/thumbnail\\/samsung-logo.jpg"}]', {{[superAdmin_id]}}, '2014-09-11 08:03:54', {{[superAdmin_id]}}, '2014-09-12 11:52:57'),
(7, 8, 1, 0, '0000-00-00 00:00:00', 'Unknown', 'unknown', 'info@qazap-unknow.com', 1, '', 'www.qazap-unknow.com', '[{"name":"unknown-logo.jpg","url":"\\/images\\/qazap\\/brands\\/unknown-logo.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"unknown-logo.jpg","medium_url":"\\/images\\/qazap\\/brands\\/medium\\/unknown-logo.jpg","thumbnail_url":"\\/images\\/qazap\\/brands\\/thumbnail\\/unknown-logo.jpg"}]', {{[superAdmin_id]}}, '2014-09-11 08:06:21', {{[superAdmin_id]}}, '2014-09-12 11:52:57'),
(8, 1, 1, 0, '0000-00-00 00:00:00', 'Adidas', 'adidas', 'info@adidas.com', 1, '', 'www.adidas.com', '[{"name":"adidas-logo.jpg","url":"\\/images\\/qazap\\/brands\\/adidas-logo.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"adidas-logo.jpg","medium_url":"\\/images\\/qazap\\/brands\\/medium\\/adidas-logo.jpg","thumbnail_url":"\\/images\\/qazap\\/brands\\/thumbnail\\/adidas-logo.jpg"}]', {{[superAdmin_id]}}, '2014-09-11 08:08:31', {{[superAdmin_id]}}, '2014-09-12 11:52:57');

--
-- Truncate table before insert `#__qazap_memberships`
--

TRUNCATE TABLE `#__qazap_memberships`;
--
-- Dumping data for table `#__qazap_memberships`
--

INSERT INTO `#__qazap_memberships` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `plan_name`, `plan_duration`, `description`, `price`, `access_to_members`, `jusergroup_id`, `jview_id`, `created_by`, `created_time`, `modified_by`, `modified_time`) VALUES
(1, 1, 1, 0, '0000-00-00 00:00:00', 'Basic Plan', '30', '', '10', '', 11, 8, {{[superAdmin_id]}}, '2014-09-11 14:31:10', {{[superAdmin_id]}}, '2014-09-12 10:38:47'),
(2, 2, 1, 0, '0000-00-00 00:00:00', 'Premium Plan', '365', '', '40', '', 12, 9, {{[superAdmin_id]}}, '2014-09-11 14:31:51', {{[superAdmin_id]}}, '2014-09-14 13:14:28');

--
-- Truncate table before insert `#__qazap_order`
--

TRUNCATE TABLE `#__qazap_order`;
--
-- Dumping data for table `#__qazap_order`
--

INSERT INTO `#__qazap_order` (`order_id`, `ordergroup_id`, `user_id`, `vendor`, `order_number`, `productTotalTax`, `productTotalDiscount`, `totalProductPrice`, `shipmentTax`, `shipmentPrice`, `paymentTax`, `paymentPrice`, `CartDiscountBeforeTax`, `CartDiscountBeforeTaxInfo`, `CartTax`, `CartTaxInfo`, `CartDiscountAfterTax`, `CartDiscountAfterTaxInfo`, `coupon_discount`, `coupon_code`, `coupon_data`, `TotalTax`, `TotalDiscount`, `Total`, `payment_method_id`, `shipment_method_id`, `order_status`, `created_by`, `created_on`, `modified_by`, `modified_on`) VALUES
(1, 1, {{[user_userid]}}, 2, 'QAZAP-1001-2014', 58.7099990845, 25.0000000000, 533.7100219727, 0.0000000000, 0.0000000000, 0.0000000000, 0.0000000000, 0.0000000000, '[]', 0.0000000000, '[]', 0.0000000000, '[]', 0.0000000000, '', '', 58.7099990845, 25.0000000000, 533.7100219727, 1, 1, 'C', {{[user_userid]}}, '2014-09-12 14:09:16', {{[user_userid]}}, '2014-09-12 14:09:16');

--
-- Truncate table before insert `#__qazap_ordergroups`
--

TRUNCATE TABLE `#__qazap_ordergroups`;
--
-- Dumping data for table `#__qazap_ordergroups`
--

INSERT INTO `#__qazap_ordergroups` (`ordergroup_id`, `user_id`, `ordergroup_number`, `order_currency`, `user_currency`, `currency_exchange_rate`, `cart_payment_method_id`, `cart_shipment_method_id`, `cart_paymentTax`, `cart_paymentPrice`, `cart_shipmentTax`, `cart_shipmentPrice`, `coupon_discount`, `coupon_code`, `cart_total`, `payment_received`, `payment_refunded`, `order_status`, `customer_note`, `ip_address`, `access_key`, `tos_accept`, `language`, `created_by`, `created_on`, `modified_by`, `modified_on`) VALUES
(1, {{[vendor_userid]}}, '20140912-145912-DA3E8E', 111, 111, 1.0000000000, 1, 1, 0.0000000000, 0.0000000000, 0.0000000000, 0.0000000000, 0.0000000000, '', 533.7100219727, 0.0000000000, 0.0000000000, 'C', '', '::1', '4e433036a5fc7e02d9a4ea05de569b5b', 1, 'en-GB', {{[user_userid]}}, '2014-09-12 14:09:16', {{[user_userid]}}, '2014-09-12 14:09:16');

--
-- Truncate table before insert `#__qazap_order_addresses`
--

TRUNCATE TABLE `#__qazap_order_addresses`;
--
-- Dumping data for table `#__qazap_order_addresses`
--

INSERT INTO `#__qazap_order_addresses` (`order_address_id`, `ordergroup_id`, `address_type`, `company`, `title`, `first_name`, `middle_name`, `last_name`, `address_1`, `address_2`, `zip`, `city`, `country`, `states_territory`, `phone`, `fax`, `mobile`, `email`) VALUES
(1, 1, 'bt', 'VIRTUEPLANET SERVICES LLP', 'COM_QAZAP_USER_MR', 'Abhishek', '', 'Das', '1266 Upen Banerjee Road', 'Flat-2A, Block-1, Southern Breeze', '700060', 'Kolkata', 99, 442, '919831637711', '', '919831637711', 'test@test.com'),
(2, 1, 'st', '', 'COM_QAZAP_USER_MR', 'My First Name', '', 'Last Name', 'Some Address Line', '', '55555', 'My City', 99, 442, '', '', '', '');

--
-- Truncate table before insert `#__qazap_order_history`
--

TRUNCATE TABLE `#__qazap_order_history`;
--
-- Dumping data for table `#__qazap_order_history`
--

INSERT INTO `#__qazap_order_history` (`order_history_id`, `ordergroup_id`, `comments`, `mail_to_buyer`, `mail_to_vendor`, `order_status`, `created_on`, `created_by`) VALUES
(1, 1, 'New order placed.', 1, 0, 'P', '2014-09-12 14:09:16', {{[user_userid]}}),
(2, 1, 'Order group status updated from Pending to Confirmed. ', 1, 1, 'C', '2014-09-12 14:09:16', {{[user_userid]}});

--
-- Truncate table before insert `#__qazap_order_items`
--

TRUNCATE TABLE `#__qazap_order_items`;
--
-- Dumping data for table `#__qazap_order_items`
--

INSERT INTO `#__qazap_order_items` (`order_items_id`, `deleted`, `order_id`, `product_id`, `group_id`, `vendor`, `product_quantity`, `stock_affected`, `stock_booked`, `product_baseprice`, `product_basepricewithVariants`, `product_salesprice`, `product_tax`, `product_discount`, `product_totalprice`, `commission`, `total_tax`, `total_discount`, `order_status`, `product_name`, `product_sku`, `product_attributes`, `product_membership`, `created_on`, `created_by`, `modified_on`, `modified_by`) VALUES
(1, 0, '1', 10, '10::0::0', 2, 1, 1, 0, 500.0000000000, 500.0000000000, 533.7100219727, 58.7099990845, 25.0000000000, 533.7100219727, 53.3709983826, 58.7099990845, 25.0000000000, 'C', 'Nikon D3200 SLR', 'CAM3', '', '', '2014-09-12 14:09:16', {{[user_userid]}}, '2014-09-12 14:09:16', {{[user_userid]}});

--
-- Truncate table before insert `#__qazap_payment_methods`
--

TRUNCATE TABLE `#__qazap_payment_methods`;
--
-- Dumping data for table `#__qazap_payment_methods`
--

INSERT INTO `#__qazap_payment_methods` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `payment_name`, `payment_description`, `payment_method`, `countries`, `logo`, `price`, `tax`, `tax_calculation`, `user_group`, `params`, `created_by`, `created_time`, `modified_by`, `modified_time`) VALUES
(1, 1, 1, NULL, NULL, 'Cash Payment', '', {{[cashplugin_id]}}, '[]', '', 0.000000, 0.000000, 'p', '[1]', '{"min_order_value":"","max_order_value":"","min_weight":"","max_weight":""}', {{[superAdmin_id]}}, '2014-09-12 12:46:27', 0, '0000-00-00 00:00:00');

--
-- Truncate table before insert `#__qazap_products`
--

TRUNCATE TABLE `#__qazap_products`;
--
-- Dumping data for table `#__qazap_products`
--

INSERT INTO `#__qazap_products` (`product_id`, `ordering`, `state`, `block`, `parent_id`, `product_sku`, `featured`, `vendor`, `urls`, `manufacturer_id`, `category_id`, `access`, `product_baseprice`, `product_customprice`, `multiple_pricing`, `dbt_rule_id`, `dat_rule_id`, `tax_rule_id`, `in_stock`, `ordered`, `booked_order`, `product_length`, `product_length_uom`, `product_width`, `product_height`, `product_weight`, `product_weight_uom`, `product_packaging`, `product_packaging_uom`, `units_in_box`, `images`, `related_categories`, `related_products`, `membership`, `params`, `checked_out`, `checked_out_time`, `created_by`, `created_time`, `modified_by`, `modified_time`, `hits`) VALUES
(1, 1, 1, 0, 0, 'MOB1', 0, 2, '', 6, 2, 1, 874.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"galaxy1.jpg","url":"\\/images\\/qazap\\/products\\/galaxy1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"galaxy1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/galaxy1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/galaxy1.jpg"},{"name":"galaxy2.jpg","url":"\\/images\\/qazap\\/products\\/galaxy2.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"galaxy2.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/galaxy2.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/galaxy2.jpg"},{"name":"galaxy3.jpg","url":"\\/images\\/qazap\\/products\\/galaxy3.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"galaxy3.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/galaxy3.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/galaxy3.jpg"},{"name":"galaxy4.jpg","url":"\\/images\\/qazap\\/products\\/galaxy4.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"galaxy4.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/galaxy4.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/galaxy4.jpg"}]', '[]', '[]', '["1","2"]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-11 11:49:34', {{[superAdmin_id]}}, '2014-09-12 09:15:50', 23),
(2, 2, 1, 0, 0, 'MOB2', 0, 2, '', 6, 2, 1, 700.0000000000, '', 0, 0, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"galaxy5.jpg","url":"\\/images\\/qazap\\/products\\/galaxy5.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"galaxy5.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/galaxy5.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/galaxy5.jpg"},{"name":"galaxy6.jpg","url":"\\/images\\/qazap\\/products\\/galaxy6.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"galaxy6.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/galaxy6.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/galaxy6.jpg"}]', '[]', '[]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 09:18:28', {{[superAdmin_id]}}, '2014-09-12 10:34:30', 25),
(3, 3, 1, 0, 0, 'MOB3', 0, 2, '', 6, 2, 1, 90.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"ace1.jpg","url":"\\/images\\/qazap\\/products\\/ace1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ace1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ace1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ace1.jpg"},{"name":"ace3.jpg","url":"\\/images\\/qazap\\/products\\/ace3.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ace3.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ace3.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ace3.jpg"}]', '[]', '[]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 09:22:42', {{[superAdmin_id]}}, '2014-09-12 10:28:11', 22),
(4, 4, 1, 0, 0, 'MOB4', 1, 2, '', 4, 2, 1, 700.0000000000, '', 0, 0, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"htc1.jpg","url":"\\/images\\/qazap\\/products\\/htc1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"htc1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/htc1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/htc1.jpg"},{"name":"htc3.jpg","url":"\\/images\\/qazap\\/products\\/htc3.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"htc3.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/htc3.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/htc3.jpg"}]', '[]', '[]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 09:25:46', {{[superAdmin_id]}}, '2014-09-12 10:32:15', 25),
(5, 5, 1, 0, 0, 'MOB5', 0, 2, '', 5, 2, 1, 680.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"bb1.jpg","url":"\\/images\\/qazap\\/products\\/bb1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"bb1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/bb1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/bb1.jpg"},{"name":"bb4.jpg","url":"\\/images\\/qazap\\/products\\/bb4.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"bb4.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/bb4.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/bb4.jpg"}]', '[]', '["1","3","4"]', '["1","2"]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 09:30:06', {{[superAdmin_id]}}, '2014-09-12 10:40:51', 23),
(6, 6, 1, 0, 0, 'CAM1', 0, 2, '', 1, 3, 1, 700.0000000000, '', 0, 0, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"canon1.jpg","url":"\\/images\\/qazap\\/products\\/canon1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"canon1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/canon1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/canon1.jpg"},{"name":"canon3.jpg","url":"\\/images\\/qazap\\/products\\/canon3.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"canon3.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/canon3.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/canon3.jpg"}]', '[]', '[]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 09:36:43', {{[superAdmin_id]}}, '2014-09-12 10:51:23', 22),
(7, 7, 1, 0, 0, 'CAM2', 0, 2, '', 2, 3, 1, 500.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"nikon1 (1).jpg","url":"\\/images\\/qazap\\/products\\/nikon1%20%281%29.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"nikon1 (1).jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/nikon1%20%281%29.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/nikon1%20%281%29.jpg"},{"name":"nikon2.jpg","url":"\\/images\\/qazap\\/products\\/nikon2.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"nikon2.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/nikon2.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/nikon2.jpg"}]', '[]', '[]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 09:44:27', {{[superAdmin_id]}}, '2014-09-12 11:10:03', 25),
(8, 8, 1, 0, 0, 'MOB6', 0, 2, '', 5, 2, 1, 680.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"bb1.jpg","url":"\\/images\\/qazap\\/products\\/bb1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"bb1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/bb1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/bb1.jpg"},{"name":"bb4.jpg","url":"\\/images\\/qazap\\/products\\/bb4.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"bb4.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/bb4.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/bb4.jpg"}]', '[]', '["1","3","4"]', '["1","2"]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 10:43:43', {{[superAdmin_id]}}, '2014-09-12 10:43:53', 23),
(9, 9, 1, 0, 7, 'CAM2', 1, 2, '', 2, 3, 1, 550.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"nikon1.jpg","url":"\\/images\\/qazap\\/products\\/nikon1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"nikon1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/nikon1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/nikon1.jpg"},{"name":"nikon5.jpg","url":"\\/images\\/qazap\\/products\\/nikon5.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"nikon5.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/nikon5.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/nikon5.jpg"}]', '[]', '[]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 10:58:13', {{[superAdmin_id]}}, '2014-09-12 11:04:43', 22),
(10, 10, 1, 0, 0, 'CAM3', 1, 2, '', 2, 3, 1, 500.0000000000, '', 0, 2, 0, 1, 99999, 1, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"nikon-r1.jpg","url":"\\/images\\/qazap\\/products\\/nikon-r1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"nikon-r1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/nikon-r1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/nikon-r1.jpg"},{"name":"nikon42.jpg","url":"\\/images\\/qazap\\/products\\/nikon42.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"nikon42.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/nikon42.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/nikon42.jpg"}]', '[]', '["6","7"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 11:07:56', {{[superAdmin_id]}}, '2014-09-12 11:11:23', 30),
(11, 11, 1, 0, 0, 'TV1', 1, 2, '', 7, 4, 1, 790.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"sony2.jpg","url":"\\/images\\/qazap\\/products\\/sony2.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"sony2.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/sony2.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/sony2.jpg"},{"name":"sony3.jpg","url":"\\/images\\/qazap\\/products\\/sony3.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"sony3.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/sony3.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/sony3.jpg"}]', '[]', '["6","7"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 11:12:58', {{[superAdmin_id]}}, '2014-09-12 11:17:33', 32),
(12, 12, 1, 0, 0, 'TV2', 0, 2, '', 6, 4, 1, 790.0000000000, '', 0, 0, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"samsung led1.jpg","url":"\\/images\\/qazap\\/products\\/samsung%20led1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"samsung led1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/samsung%20led1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/samsung%20led1.jpg"},{"name":"sony4.jpg","url":"\\/images\\/qazap\\/products\\/sony4.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"sony4.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/sony4.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/sony4.jpg"}]', '["3","4"]', '["11"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 11:21:12', {{[superAdmin_id]}}, '2014-09-12 11:23:09', 32),
(13, 13, 1, 0, 0, 'TV3', 0, 2, '', 6, 4, 1, 500.0000000000, '', 0, 0, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"sony1.jpg","url":"\\/images\\/qazap\\/products\\/sony1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"sony1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/sony1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/sony1.jpg"}]', '[]', '["11"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 11:26:12', {{[superAdmin_id]}}, '2014-09-12 11:28:11', 32),
(14, 14, 1, 0, 0, 'SHOE1', 0, 2, '', 8, 5, 1, 85.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"ad1.jpg","url":"\\/images\\/qazap\\/products\\/ad1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ad1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ad1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ad1.jpg"},{"name":"ad3.jpg","url":"\\/images\\/qazap\\/products\\/ad3.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ad3.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ad3.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ad3.jpg"},{"name":"ad4.jpg","url":"\\/images\\/qazap\\/products\\/ad4.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ad4.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ad4.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ad4.jpg"},{"name":"ad5.jpg","url":"\\/images\\/qazap\\/products\\/ad5.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ad5.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ad5.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ad5.jpg"}]', '[]', '["11"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 11:31:04', {{[superAdmin_id]}}, '2014-09-12 11:48:40', 34),
(15, 15, 1, 0, 0, 'SHOE2', 0, 2, '', 8, 5, 1, 80.0000000000, '', 0, 0, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"ad13.jpg","url":"\\/images\\/qazap\\/products\\/ad13.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ad13.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ad13.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ad13.jpg"},{"name":"ad27.jpg","url":"\\/images\\/qazap\\/products\\/ad27.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ad27.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ad27.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ad27.jpg"},{"name":"ad36.jpg","url":"\\/images\\/qazap\\/products\\/ad36.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ad36.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ad36.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ad36.jpg"},{"name":"ad48.jpg","url":"\\/images\\/qazap\\/products\\/ad48.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"ad48.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/ad48.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/ad48.jpg"}]', '[]', '["14"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 11:38:19', {{[superAdmin_id]}}, '2014-09-12 11:40:42', 33),
(16, 16, 1, 0, 0, 'SHOE3', 0, 2, '', 7, 5, 1, 85.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"puma1.jpg","url":"\\/images\\/qazap\\/products\\/puma1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"puma1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/puma1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/puma1.jpg"},{"name":"puma3.jpg","url":"\\/images\\/qazap\\/products\\/puma3.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"puma3.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/puma3.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/puma3.jpg"},{"name":"puma4.jpg","url":"\\/images\\/qazap\\/products\\/puma4.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"puma4.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/puma4.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/puma4.jpg"},{"name":"puma5.jpg","url":"\\/images\\/qazap\\/products\\/puma5.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"puma5.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/puma5.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/puma5.jpg"}]', '[]', '["11"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 11:42:53', {{[superAdmin_id]}}, '2014-09-12 12:20:57', 33),
(17, 17, 1, 0, 0, 'MEN1', 0, 2, '', 0, 8, 1, 90.0000000000, '', 0, 0, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"men1.jpg","url":"\\/images\\/qazap\\/products\\/men1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"men1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/men1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/men1.jpg"},{"name":"men2.jpg","url":"\\/images\\/qazap\\/products\\/men2.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"men2.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/men2.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/men2.jpg"}]', '[]', '["11"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 12:17:52', {{[superAdmin_id]}}, '2014-09-12 12:27:47', 34),
(18, 18, 1, 0, 0, 'MEN2', 0, 2, '', 0, 8, 1, 85.0000000000, '', 0, 2, 0, 1, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"men2.jpg","url":"\\/images\\/qazap\\/products\\/men2.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"men2.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/men2.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/men2.jpg"},{"name":"men1.jpg","url":"\\/images\\/qazap\\/products\\/men1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"men1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/men1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/men1.jpg"}]', '[]', '["11"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 12:24:25', {{[superAdmin_id]}}, '2014-09-12 12:32:17', 33),
(19, 19, 1, 0, 0, 'MEN3', 0, 2, '', 0, 8, 1, 110.0000000000, '', 0, 2, 0, 0, 100000, 0, 0, '', '1', '', '', '', '24', '', '14', '', '[{"name":"men3.jpg","url":"\\/images\\/qazap\\/products\\/men3.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"men3.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/men3.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/men3.jpg"},{"name":"men1.jpg","url":"\\/images\\/qazap\\/products\\/men1.jpg","type":"image\\/jpeg","filetype":"INTERNAL","remove_url":"men1.jpg","medium_url":"\\/images\\/qazap\\/products\\/medium\\/men1.jpg","thumbnail_url":"\\/images\\/qazap\\/products\\/thumbnail\\/men1.jpg"}]', '[]', '["16","17","18"]', '[]', '{"product_layout":"","show_icon":"","print_view_link":"","pdf_view_icon":"","email_icon":"","show_availablity":"","availability_day_info":"","in_stock_image":"","out_of_stock_image":"","ask_seller":"","show_stock":"","show_manufacturer":"","show_seller":"","show_category_product":"","show_rating":"","show_link_category_product":"","low_stock_notification":"","minimum_purchase_quantity":"","maximum_purchase_quantity":"","purchase_quantity_steps":"","stockout_action":"","contact_for_price":"","available_from":"","available_end":""}', 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-12 12:30:21', {{[superAdmin_id]}}, '2014-09-12 12:32:01', 33);

--
-- Truncate table before insert `#__qazap_product_details`
--

TRUNCATE TABLE `#__qazap_product_details`;
--
-- Dumping data for table `#__qazap_product_details`
--

INSERT INTO `#__qazap_product_details` (`product_details_id`, `product_id`, `language`, `product_name`, `product_alias`, `short_description`, `product_description`, `metakey`, `metadesc`, `metadata`) VALUES
(2, 1, 'en-GB', 'Samsung Galaxy S3', 'samsung-galaxy-s3', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(3, 2, 'en-GB', 'Samsung Galaxy', 'samsung-galaxy', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(4, 4, 'en-GB', 'HTC One X', 'htc-one-x', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(5, 6, 'en-GB', 'Canon EOS 550D', 'canon-eos-550d', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(6, 7, 'en-GB', 'Nikon D3100 SLR', 'nikon-d3100-slr', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(7, 3, 'en-GB', 'Galaxy Ace S5830', 'galaxy-ace-s5830', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(8, 5, 'en-GB', 'BlackBerry Bold 9650', 'blackberry-bold-9650', '', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(9, 8, 'en-GB', 'BlackBerry Bold', 'blackberry-bold', '', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(10, 9, 'en-GB', 'Nikon D3100 With Lens', 'nikon-d3100-with-lens', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(11, 10, 'en-GB', 'Nikon D3200 SLR', 'nikon-d3200-slr-2', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(12, 11, 'en-GB', 'Awsome LED TV', 'awsome-led-tv', '', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(13, 12, 'en-GB', 'Samsung UN40B7000', 'samsung-un40b7000', '', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(14, 13, 'en-GB', 'Smart TV', 'smart-tv', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(15, 14, 'en-GB', 'Addidas Barricade Shoe', 'addidas-barricade-shoe', '', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(16, 15, 'en-GB', 'Addidas Predito Shoe', 'addidas-predito-shoe', '', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(17, 16, 'en-GB', 'Men Black Shoe', 'men-black-shoe', '', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(18, 17, 'en-GB', 'Black Shirt', 'black-shirt', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(19, 18, 'en-GB', 'Black Nice Shirt', 'black-nice-shirt', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}'),
(20, 19, 'en-GB', 'Men Shirt', 'men-shirt', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '', '', '{"page_title":"","author":"","robots":""}');

--
-- Truncate table before insert `#__qazap_shipment_methods`
--

TRUNCATE TABLE `#__qazap_shipment_methods`;
--
-- Dumping data for table `#__qazap_shipment_methods`
--

INSERT INTO `#__qazap_shipment_methods` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `shipment_name`, `shipment_description`, `shipment_method`, `countries`, `logo`, `price`, `tax`, `tax_calculation`, `user_group`, `params`, `created_by`, `created_time`, `modified_by`, `modified_time`) VALUES
(1, 1, 1, 0, '0000-00-00 00:00:00', 'Collect from Store', '', {{[collectplugin_id]}}, '', '', 0.000000, 0.000000, 'p', '[1]', '{"min_order_value":"","max_order_value":"","min_weight":"","max_weight":""}', {{[superAdmin_id]}}, '2014-09-12 12:58:04', {{[superAdmin_id]}}, '2014-09-12 12:58:16'),
(2, 2, 1, NULL, NULL, 'Courier', '', {{[collectplugin_id]}}, '', '', 50.000000, 0.000000, 'p', '[1]', '{"min_order_value":"","max_order_value":"","min_weight":"","max_weight":""}', {{[superAdmin_id]}}, '2014-09-12 12:58:55', 0, '0000-00-00 00:00:00');

--
-- Truncate table before insert `#__qazap_shop`
--

TRUNCATE TABLE `#__qazap_shop`;
--
-- Dumping data for table `#__qazap_shop`
--

INSERT INTO `#__qazap_shop` (`shop_id`, `lang`, `name`, `company`, `contact_person`, `address_1`, `address_2`, `city`, `state`, `country`, `zip`, `phone_1`, `phone_2`, `fax`, `mobile`, `vat`, `additional_info`, `tos`, `description`, `modified_time`, `modified_by`) VALUES
(1, '*', 'Qazap', 'My Company', 'Contact Person Name', 'Some Address Line', '', 'My City', 442, 99, '444232', '+912351735271', '', '', '', '', '', '<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>\r\n<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>\r\n<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>\r\n<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>\r\n<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>\r\n<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>\r\n<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>', '', '2014-05-07 12:02:06', {{[superAdmin_id]}});

--
-- Truncate table before insert `#__qazap_userinfos`
--

TRUNCATE TABLE `#__qazap_userinfos`;
--
-- Dumping data for table `#__qazap_userinfos`
--

INSERT INTO `#__qazap_userinfos` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `created_by`, `created_time`, `modified_by`, `modified_time`, `user_id`, `address_type`, `address_name`, `company`, `title`, `first_name`, `middle_name`, `last_name`, `address_1`, `address_2`, `zip`, `city`, `country`, `states_territory`, `phone`, `fax`, `mobile`, `email`) VALUES
(1, 1, 0, 0, '0000-00-00 00:00:00', {{[user_userid]}}, '2014-09-12 13:25:28', {{[superAdmin_id]}}, '2014-09-16 09:20:00', {{[user_userid]}}, 'bt', '', 'User Company', 'COM_QAZAP_USER_MR', 'Test', '', 'User', 'Some Address Line', '', '555515', 'My City', 99, 442, '+91 23018278278', '', '', 'testuser@qazap.com'),
(2, 2, 1, 0, '0000-00-00 00:00:00', {{[user_userid]}}, '2014-09-12 14:08:02', 0, '0000-00-00 00:00:00', {{[user_userid]}}, 'st', 'Shipping Address', '', 'COM_QAZAP_USER_MR', 'My First Name', NULL, 'Last Name', 'Some Address Line', '', '55555', 'My City', 99, 442, NULL, NULL, NULL, NULL),
(3, 3, 0, 0, '0000-00-00 00:00:00', {{[vendor_userid]}}, '2014-09-14 08:38:18', {{[vendor_userid]}}, '2014-09-14 12:43:36', {{[vendor_userid]}}, 'bt', '', '', 'COM_QAZAP_USER_MR', 'Demo', '', 'User', 'Some Address Line', '', '55555', 'My City', 99, 442, '+91 12345678910', '', '', 'demouser@qazap.com');

--
-- Truncate table before insert `#__qazap_vendor`
--

TRUNCATE TABLE `#__qazap_vendor`;
--
-- Dumping data for table `#__qazap_vendor`
--

INSERT INTO `#__qazap_vendor` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `created_by`, `created_time`, `modified_by`, `modified_time`, `vendor_admin`, `vendor_group_id`, `shop_name`, `alias`, `category_list`, `shipment_methods`, `title`, `firstname`, `lastname`, `address1`, `address2`, `country`, `email`, `mobile`, `fax`, `image`, `states`, `shop_description`) VALUES
(2, 2, 1, 0, '0000-00-00 00:00:00', {{[superAdmin_id]}}, '2014-09-11 09:07:45', {{[superAdmin_id]}}, '2014-09-12 12:43:22', {{[vendor_userid]}}, 1, 'Demo Vendor', 'demo-vendor', '', '0', 'COM_QAZAP_', 'Demo', 'Vendor', 'Some Address Line', '', '99', 'demovendor@qazap.com', '', '', NULL, '442', '');

--
-- Truncate table before insert `#__qazap_vendor_groups`
--

TRUNCATE TABLE `#__qazap_vendor_groups`;
--
-- Dumping data for table `#__qazap_vendor_groups`
--

INSERT INTO `#__qazap_vendor_groups` (`vendor_group_id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `title`, `description`, `commission`, `jusergroup_id`, `jview_id`, `created_by`, `created_time`, `modified_by`, `modified_time`) VALUES
(1, 1, 1, 0, '0000-00-00 00:00:00', 'Default Vendor Group', '', 10.000, {{[jusergroup_id]}}, {{[jview_id]}}, {{[superAdmin_id]}}, '2014-09-11 08:14:27', 0, '0000-00-00 00:00:00');